name: IAC

on: push

jobs:
  apply:
    name: Apply terraform plan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      TF_ACTION_WORKING_DIR: '.'
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.2.4
      
    - name: Terraform Execute
      run: |
        cd IAC/
        terraform destroy
        terraform init
        terraform plan
        terraform apply --auto-approve
